/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Loader from '../components/Loader/Loader';
import WorksCard from '../components/WorksCard/WorksCard';
import { MantineProvider } from '@mantine/core';
import Link from 'next/link';
import { client } from 'libs/client';
import MainVisual from '../components/MainVisual/MainVisual';
import ServiceSection from '../components/ServiceSection/ServiceSection';
import Procedure from '../components/Procedure/Procedure';

export default function Home({ blog }) {
  return (
    <>
      <Head>
        <title>Shumi | 横浜市のWebブランディング会社</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Montserrat:ital,wght@1,700&display=swap"
          rel="stylesheet"
        />
        <link href="http://fonts.googleapis.com/earlyaccess/notosansjp.css"></link>
      </Head>
      <main className={styles.main}>
        <MainVisual />
        <ServiceSection />
        <WorksCard />
        {/* <div>
          <ul className="flex gap-10">
            {blog.map((blog) => (
              // eslint-disable-next-line react/jsx-key
              <li key={blog.id}>
                <Link href={`/blog/${blog.id}`}>
                  <img
                    src={blog.eyecatch.url}
                    width={640}
                    height={320}
                    alt="ブログアイキャッチ画像"
                  />
                  <h3 className="mt-8 text-xl font-bold">{blog.title}</h3>
                </Link>
              </li>
            ))}
          </ul>
        </div> */}
        <Procedure />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const data = await client.get({ endpoint: 'blog' });
  return {
    props: {
      blog: data.contents,
    },
  };
};
