/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Loader from '../components/Loader/Loader';
import WorksCard from '../components/WorksCard/WorksCard';
import { MantineProvider } from '@mantine/core';
import Link from 'next/link';
import { client } from 'libs/client';
import ServiceSection from '../components/ServiceSection/ServiceSection';
import Procedure from '../components/Procedure/Procedure';
import BlogTop from '../components/blog/BlogTop';
import MainVisual from '../components/MainVisual/MainVisual';

export default function Home({ blog }) {
  return (
    <>
      <Head>
        <title>Shumi | 横浜市のWebブランディング会社</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Montserrat:ital,wght@1,700&display=swap"
          rel="stylesheet"
        />
        <link href="http://fonts.googleapis.com/earlyaccess/notosansjp.css"></link>
      </Head>
      <main className={styles.main}>
        <MainVisual />
        <ServiceSection />
        <WorksCard />
        <div className="max-w-screen-xl mx-auto px-4">
          <ul className="grid md:grid-cols-3 lg:grid-cols-3 gap-4">
            {blog.map((blog) => (
              <li key={blog.id} className="list-none">
                <Link href={`/blog/${blog.id}`}>
                  <img
                    src={blog.eyecatch.url}
                    sizes="100vw"
                    style={{
                      width: '100%',
                      maxWidth: '100%',
                      height: 'auto',
                    }}
                    alt="ブログアイキャッチ画像"
                  />
                  <h3 className="mt-4 text-md font-bold">{blog.title}</h3>
                </Link>
              </li>
            ))}
          </ul>
        </div>
        <Procedure />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const data = await client.get({
    endpoint: 'blog',
    queries: { limit: 3, orders: '-publishedAt' }, // 最新3記事を取得
  });
  return {
    props: {
      blog: data.contents,
    },
  };
};
