/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { client } from 'libs/client';
import Loader from '../components/Loader/Loader';
import WorksCard from '../components/WorksCard/WorksCard';

export default function Home({ blog }) {
  return (
    <>
      <Head>
        <title>Shumi | 横浜市のWebブランディング会社</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Loader />
        <div>
          <ul className="flex gap-10">
            {blog.map((blog) => (
              // eslint-disable-next-line react/jsx-key
              <li key={blog.id}>
                <Link href={`/blog/${blog.id}`}>
                  <img
                    src={blog.eyecatch.url}
                    width={640}
                    height={320}
                    alt="ブログアイキャッチ画像"
                  />
                  <h3 className="mt-8 text-xl font-bold">{blog.title}</h3>
                </Link>
              </li>
            ))}
          </ul>
        </div>
        <WorksCard />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const data = await client.get({ endpoint: 'blog' });
  return {
    props: {
      blog: data.contents,
    },
  };
};
